<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product_details')->insert([

            [
                'id' => 1,
                'product_id' => 1,
                'color_id' => null,
                'size_id' => 1,
                'price' => '400',
                'stock' => 50,
                'status' => 'available',
                'created_at' => '2025-09-07 10:52:52',
                'updated_at' => '2025-09-07 10:52:52',
            ],
            [
                'id' => 2,
                'product_id' => 1,
                'color_id' => null,
                'size_id' => 2,
                'price' => '400',
                'stock' => 50,
                'status' => 'available',
                'created_at' => '2025-09-07 10:52:58',
                'updated_at' => '2025-09-07 10:52:58',
            ],
            [
                'id' => 3,
                'product_id' => 1,
                'color_id' => null,
                'size_id' => 3,
                'price' => '400',
                'stock' => 50,
                'status' => 'available',
                'created_at' => '2025-09-07 10:53:05',
                'updated_at' => '2025-09-07 10:53:05',
            ],
            [
                'id' => 4,
                'product_id' => 1,
                'color_id' => null,
                'size_id' => 4,
                'price' => '400',
                'stock' => 50,
                'status' => 'available',
                'created_at' => '2025-09-07 10:53:12',
                'updated_at' => '2025-09-07 10:53:12',
            ],
            [
                'id' => 5,
                'product_id' => 2,
                'color_id' => 1,
                'size_id' => 5,
                'price' => '650',
                'stock' => 13,
                'status' => 'available',
                'created_at' => '2025-09-07 11:16:51',
                'updated_at' => '2025-09-07 11:16:51',
            ],
            [
                'id' => 6,
                'product_id' => 2,
                'color_id' => 1,
                'size_id' => 6,
                'price' => '650',
                'stock' => 13,
                'status' => 'available',
                'created_at' => '2025-09-07 11:17:05',
                'updated_at' => '2025-09-07 11:17:05',
            ],
            [
                'id' => 7,
                'product_id' => 2,
                'color_id' => 1,
                'size_id' => 7,
                'price' => '650',
                'stock' => 13,
                'status' => 'available',
                'created_at' => '2025-09-07 11:17:10',
                'updated_at' => '2025-09-07 11:17:10',
            ],
            [
                'id' => 11,
                'product_id' => 2,
                'color_id' => 2,
                'size_id' => 5,
                'price' => '650',
                'stock' => 15,
                'status' => 'available',
                'created_at' => '2025-09-07 11:36:32',
                'updated_at' => '2025-09-07 11:36:32',
            ],
            [
                'id' => 12,
                'product_id' => 2,
                'color_id' => 2,
                'size_id' => 6,
                'price' => '650',
                'stock' => 15,
                'status' => 'available',
                'created_at' => '2025-09-07 11:36:36',
                'updated_at' => '2025-09-07 11:36:36',
            ],
            [
                'id' => 13,
                'product_id' => 2,
                'color_id' => 2,
                'size_id' => 7,
                'price' => '650',
                'stock' => 15,
                'status' => 'available',
                'created_at' => '2025-09-07 11:36:39',
                'updated_at' => '2025-09-07 11:36:39',
            ],
            [
                'id' => 14,
                'product_id' => 2,
                'color_id' => 3,
                'size_id' => 5,
                'price' => '650',
                'stock' => 65,
                'status' => 'available',
                'created_at' => '2025-09-07 11:39:34',
                'updated_at' => '2025-09-07 11:39:34',
            ],
            [
                'id' => 15,
                'product_id' => 2,
                'color_id' => 3,
                'size_id' => 6,
                'price' => '650',
                'stock' => 65,
                'status' => 'available',
                'created_at' => '2025-09-07 11:39:37',
                'updated_at' => '2025-09-07 11:39:37',
            ],
            [
                'id' => 16,
                'product_id' => 2,
                'color_id' => 3,
                'size_id' => 7,
                'price' => '650',
                'stock' => 63,
                'status' => 'available',
                'created_at' => '2025-09-07 11:39:41',
                'updated_at' => '2025-09-07 16:53:44',
            ],
            [
                'id' => 17,
                'product_id' => 2,
                'color_id' => 4,
                'size_id' => 5,
                'price' => '650',
                'stock' => 25,
                'status' => 'available',
                'created_at' => '2025-09-07 11:42:21',
                'updated_at' => '2025-09-07 11:42:21',
            ],
            [
                'id' => 20,
                'product_id' => 2,
                'color_id' => 4,
                'size_id' => 6,
                'price' => '650',
                'stock' => 25,
                'status' => 'available',
                'created_at' => '2025-09-07 11:48:21',
                'updated_at' => '2025-09-07 11:48:21',
            ],
            [
                'id' => 21,
                'product_id' => 2,
                'color_id' => 4,
                'size_id' => 7,
                'price' => '650',
                'stock' => 25,
                'status' => 'available',
                'created_at' => '2025-09-07 11:48:23',
                'updated_at' => '2025-09-07 11:48:23',
            ],
            [
                'id' => 22,
                'product_id' => 3,
                'color_id' => null,
                'size_id' => 8,
                'price' => '350',
                'stock' => 150,
                'status' => 'available',
                'created_at' => '2025-09-07 12:01:58',
                'updated_at' => '2025-09-07 12:01:58',
            ],
            [
                'id' => 23,
                'product_id' => 3,
                'color_id' => null,
                'size_id' => 9,
                'price' => '350',
                'stock' => 150,
                'status' => 'available',
                'created_at' => '2025-09-07 12:02:02',
                'updated_at' => '2025-09-07 12:02:02',
            ],
            [
                'id' => 24,
                'product_id' => 3,
                'color_id' => null,
                'size_id' => 10,
                'price' => '350',
                'stock' => 150,
                'status' => 'available',
                'created_at' => '2025-09-07 12:02:07',
                'updated_at' => '2025-09-07 12:02:07',
            ],
            [
                'id' => 25,
                'product_id' => 3,
                'color_id' => null,
                'size_id' => 11,
                'price' => '350',
                'stock' => 150,
                'status' => 'available',
                'created_at' => '2025-09-07 12:02:10',
                'updated_at' => '2025-09-07 12:02:10',
            ],
            [
                'id' => 26,
                'product_id' => 4,
                'color_id' => null,
                'size_id' => null,
                'price' => '27000',
                'stock' => 90,
                'status' => 'available',
                'created_at' => '2025-09-07 12:10:04',
                'updated_at' => '2025-09-07 12:10:04',
            ],
            [
                'id' => 27,
                'product_id' => 5,
                'color_id' => null,
                'size_id' => null,
                'price' => '32000',
                'stock' => 63,
                'status' => 'available',
                'created_at' => '2025-09-07 12:11:39',
                'updated_at' => '2025-09-07 16:53:44',
            ],
            [
                'id' => 28,
                'product_id' => 6,
                'color_id' => null,
                'size_id' => null,
                'price' => '40000',
                'stock' => 21,
                'status' => 'available',
                'created_at' => '2025-09-07 12:16:44',
                'updated_at' => '2025-09-08 14:31:56',
            ],
            [
                'id' => 29,
                'product_id' => 7,
                'color_id' => null,
                'size_id' => null,
                'price' => '28000',
                'stock' => 45,
                'status' => 'available',
                'created_at' => '2025-09-07 12:35:56',
                'updated_at' => '2025-09-07 12:35:56',
            ],
            [
                'id' => 30,
                'product_id' => 8,
                'color_id' => null,
                'size_id' => null,
                'price' => '37000',
                'stock' => 40,
                'status' => 'available',
                'created_at' => '2025-09-07 12:55:50',
                'updated_at' => '2025-09-08 14:30:32',
            ],
            [
                'id' => 31,
                'product_id' => 9,
                'color_id' => null,
                'size_id' => null,
                'price' => '61000',
                'stock' => 32,
                'status' => 'available',
                'created_at' => '2025-09-07 12:57:54',
                'updated_at' => '2025-09-08 14:30:32',
            ],
            [
                'id' => 32,
                'product_id' => 10,
                'color_id' => null,
                'size_id' => null,
                'price' => '46000',
                'stock' => 45,
                'status' => 'available',
                'created_at' => '2025-09-08 20:59:45',
                'updated_at' => '2025-09-08 20:59:45',
            ],
            [
                'id' => 33,
                'product_id' => 11,
                'color_id' => null,
                'size_id' => null,
                'price' => '52300',
                'stock' => 87,
                'status' => 'available',
                'created_at' => '2025-09-08 21:04:06',
                'updated_at' => '2025-09-08 21:04:06',
            ],
            [
                'id' => 34,
                'product_id' => 12,
                'color_id' => null,
                'size_id' => null,
                'price' => '59000',
                'stock' => 13,
                'status' => 'available',
                'created_at' => '2025-09-08 21:06:19',
                'updated_at' => '2025-09-08 21:06:19',
            ],
            [
                'id' => 35,
                'product_id' => 13,
                'color_id' => null,
                'size_id' => null,
                'price' => '61000',
                'stock' => 53,
                'status' => 'available',
                'created_at' => '2025-09-08 21:08:06',
                'updated_at' => '2025-09-08 21:08:06',
            ],
            [
                'id' => 36,
                'product_id' => 14,
                'color_id' => null,
                'size_id' => null,
                'price' => '9000',
                'stock' => 15,
                'status' => 'available',
                'created_at' => '2025-09-08 21:12:19',
                'updated_at' => '2025-09-08 21:12:19',
            ],
            [
                'id' => 37,
                'product_id' => 15,
                'color_id' => null,
                'size_id' => null,
                'price' => '51000',
                'stock' => 67,
                'status' => 'available',
                'created_at' => '2025-09-08 21:13:54',
                'updated_at' => '2025-09-08 21:13:54',
            ],
            [
                'id' => 38,
                'product_id' => 16,
                'color_id' => null,
                'size_id' => null,
                'price' => '6000',
                'stock' => 48,
                'status' => 'available',
                'created_at' => '2025-09-08 21:15:23',
                'updated_at' => '2025-09-08 21:15:23',
            ],
            [
                'id' => 39,
                'product_id' => 17,
                'color_id' => null,
                'size_id' => null,
                'price' => '200',
                'stock' => 90,
                'status' => 'available',
                'created_at' => '2025-09-08 21:21:30',
                'updated_at' => '2025-09-08 21:21:30',
            ],
            [
                'id' => 40,
                'product_id' => 18,
                'color_id' => null,
                'size_id' => null,
                'price' => '800',
                'stock' => 222,
                'status' => 'available',
                'created_at' => '2025-09-08 21:23:43',
                'updated_at' => '2025-09-08 21:23:43',
            ],
            [
                'id' => 41,
                'product_id' => 19,
                'color_id' => null,
                'size_id' => null,
                'price' => '2000',
                'stock' => 56,
                'status' => 'available',
                'created_at' => '2025-09-08 21:25:59',
                'updated_at' => '2025-09-08 21:25:59',
            ],
            [
                'id' => 42,
                'product_id' => 20,
                'color_id' => null,
                'size_id' => null,
                'price' => '1600',
                'stock' => 78,
                'status' => 'available',
                'created_at' => '2025-09-08 21:27:53',
                'updated_at' => '2025-09-08 21:27:53',
            ],
            [
                'id' => 43,
                'product_id' => 21,
                'color_id' => null,
                'size_id' => null,
                'price' => '800',
                'stock' => 67,
                'status' => 'available',
                'created_at' => '2025-09-08 21:29:19',
                'updated_at' => '2025-09-08 21:29:19',
            ],
            [
                'id' => 44,
                'product_id' => 22,
                'color_id' => null,
                'size_id' => 12,
                'price' => '1000',
                'stock' => 69,
                'status' => 'available',
                'created_at' => '2025-09-08 21:32:24',
                'updated_at' => '2025-09-08 21:32:24',
            ],
            [
                'id' => 45,
                'product_id' => 22,
                'color_id' => null,
                'size_id' => 13,
                'price' => '1000',
                'stock' => 69,
                'status' => 'available',
                'created_at' => '2025-09-08 21:32:28',
                'updated_at' => '2025-09-08 21:32:28',
            ],
            [
                'id' => 46,
                'product_id' => 22,
                'color_id' => null,
                'size_id' => 14,
                'price' => '1000',
                'stock' => 69,
                'status' => 'available',
                'created_at' => '2025-09-08 21:32:32',
                'updated_at' => '2025-09-08 21:32:32',
            ],
            [
                'id' => 47,
                'product_id' => 22,
                'color_id' => null,
                'size_id' => 15,
                'price' => '1000',
                'stock' => 69,
                'status' => 'available',
                'created_at' => '2025-09-08 21:32:36',
                'updated_at' => '2025-09-08 21:32:36',
            ],
            [
                'id' => 48,
                'product_id' => 23,
                'color_id' => null,
                'size_id' => null,
                'price' => '400',
                'stock' => 234,
                'status' => 'available',
                'created_at' => '2025-09-08 21:37:07',
                'updated_at' => '2025-09-08 21:37:07',
            ],
            [
                'id' => 49,
                'product_id' => 24,
                'color_id' => null,
                'size_id' => null,
                'price' => '1500',
                'stock' => 23,
                'status' => 'available',
                'created_at' => '2025-09-08 21:39:12',
                'updated_at' => '2025-09-08 21:39:12',
            ],
            [
                'id' => 50,
                'product_id' => 25,
                'color_id' => null,
                'size_id' => null,
                'price' => '1100',
                'stock' => 34,
                'status' => 'available',
                'created_at' => '2025-09-08 21:40:15',
                'updated_at' => '2025-09-08 21:40:15',
            ],
            [
                'id' => 51,
                'product_id' => 26,
                'color_id' => null,
                'size_id' => null,
                'price' => '1000',
                'stock' => 58,
                'status' => 'available',
                'created_at' => '2025-09-08 21:41:19',
                'updated_at' => '2025-09-08 21:41:19',
            ],
            [
                'id' => 52,
                'product_id' => 27,
                'color_id' => null,
                'size_id' => null,
                'price' => '3000',
                'stock' => 24,
                'status' => 'available',
                'created_at' => '2025-09-08 21:44:33',
                'updated_at' => '2025-09-08 21:44:33',
            ],
        ]);
    }
}
